# Generated by Django 2.1.5 on 2019-06-04 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20190601_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date_planned',
        ),
        migrations.AddField(
            model_name='events',
            name='datetime_planned',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='events',
            field=models.ManyToManyField(blank=True, default=None, to='social.Events'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='memories',
            field=models.ManyToManyField(blank=True, default=None, to='social.Memories'),
        ),
    ]
