# Generated by Django 2.1.5 on 2019-06-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
