# Generated by Django 2.1.5 on 2019-06-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190604_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultgroup.png', upload_to=''),
        ),
    ]
