# Generated by Django 2.1.5 on 2019-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20190604_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='icon',
            field=models.ImageField(default='hangout logo.png', upload_to=''),
        ),
    ]
