# Generated by Django 2.1.5 on 2019-06-08 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='messages',
        ),
        migrations.AddField(
            model_name='myuser',
            name='messages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='accounts.Message'),
            preserve_default=False,
        ),
    ]
